---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
      #http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/,http://eureka-primary:8011/eureka/
# Allow Eureka to recognize two apps of the same type 
# on the same host as separate instances (see bonus step):
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: 8050

---
spring:
  profiles: cold-noun
words: icicle,refrigerator,blizzard,snowball
server:
  port: 8051
